defaults:
  - _self_
  - server_configs: fuzzing

# root folders
project_root: /home/erdos/workspace/MoDitector
save_root: /home/erdos/workspace/results/MoDitector/debug_testing
save_root_testing: ${save_root}/testing

# runner
log_level: 'DEBUG'
resume: true
random_seed: 1000
timeout: 600 # watchdog timeout
debug: false
record: false # carla record

# testing (fuzzing)
entry_point_fuzzer: fuzzer.suites:RandomFuzzer
entry_point_scenario: scenario.pattern:WaypointScenario
entry_point_target_agent: ads.systems.Pylot.ERDOSRootCauseAgent:ERDOSRootCauseAgent
config_target_agent: /home/erdos/workspace/MoDitector/configs/pylot_configs/intersection_straight_bak_RandomFuzzer.conf
time_limit: 12
seed_path: /home/erdos/workspace/MoDitector/data/seeds/intersection_straight_bak.json
# mutator:
mutator_vehicle_num: 10
mutator_walker_num: 10
mutator_static_num: 0

# env config
gpu: 0

hydra:
  job:
    chdir: True